run:

linters:
  disable-all: true
  enable:
    - errcheck
    - ineffassign
    - govet
    - gosimple

issues:
  exclude-rules:
    - path: '(.+)_test\.go'
      text: ".*GetPaymentHistory is deprecated: Payment history has migrated to chats"
    - path: '(.+)testutil\.go'
      text: ".*GetPaymentHistory is deprecated: Payment history has migrated to chats"
